wrong access to nomeclature table fields at save in products
ATM-Consulting/dolibarr_module_nomenclature pull request #242
Opened 2023-06-23 11:18 UTC by splohmer

save buttons on nomenclature tab in products not working due to access to wrong nomenclature table fields

2023-07-12 12:09 UTC, atm-john commented on class/nomenclature.class.php
> +    static function resetDefaultNomenclature(&$PDOdb, $fk_product, $object_type)
```suggestion
    static function resetDefaultNomenclature(&$PDOdb, $fk_product, $object_type = 'product')
```

2023-07-12 12:15 UTC, atm-john requested changes

2023-07-12 12:15 UTC, atm-john commented on class/nomenclature.class.php
> +    static function resetDefaultNomenclature(&$PDOdb, $fk_product, $object_type)
```suggestion
    static function resetDefaultNomenclature(&$PDOdb, $fk_object, $object_type = 'product')
```
To avoid fatal errors for external modules calling this method for old product behavior

2023-07-12 12:15 UTC, atm-john commented on class/nomenclature.class.php
> +		return $PDOdb->Execute('UPDATE '.MAIN_DB_PREFIX.'nomenclature SET is_default = 0 WHERE fk_object = '.(int) $fk_product.' AND object_type = "'.$object_type.'"');
```suggestion
		global $db;
		return $PDOdb->Execute('UPDATE '.MAIN_DB_PREFIX.'nomenclature SET is_default = 0 WHERE fk_object = '.(int) $fk_object.' AND object_type = "'.$db->escape($object_type).'"');
```

2023-07-12 12:17 UTC, atm-john commented
Thanks for your contribution.
You have conflict to resolve.

2023-07-31 11:49 UTC, splohmer commented
Hi @atm-john,
conflicts are solved.

2023-07-31 12:14 UTC, atm-john commented
hi @splohmer, have you see my suggested changes ?

2023-08-01 05:27 UTC, splohmer commented
Hi @atm-john,
sorry. somehow I missed them. I will go through it and check it.

Regards,
Sven

2023-08-01 05:39 UTC, splohmer commented
Hi @atm-john,
thanks for your suggestions. I took over all of them. Better for backward compatibility and security.

Regards,
Sven

2023-08-21 14:23 UTC, merged